### ISSUE TITLE
Tweeten won't update to 5.0.4

### ISSUE THREAD

**Issue by ThaTiemsz** [MehediH/Tweeten#181]
The app just closes after I click the Install Now button without actually installing the update, therefore making the update prompt reappear when I reopen the app.

[main.log](https://github.com/MehediH/Tweeten/files/4810330/main.log)
[main.old.log](https://github.com/MehediH/Tweeten/files/4810331/main.old.log)

**Comment by fakearian** [comment]
Same issue 


[main.log](https://github.com/MehediH/Tweeten/files/4810344/main.log)

**Comment by MehediH** [comment]
@ThaTiemsz @fakearian Did you both have the "Minimize to tray" option enabled?

**Comment by fakearian** [comment]
@MehediH  I did not

**Comment by ThaTiemsz** [comment]
@MehediH I didn't either

**Comment by MehediH** [comment]
@ThaTiemsz @fakearian If you both try to download Tweeten 5.3 from here https://github.com/MehediH/Tweeten/releases/tag/v5.0.3, install it, and then try to update to 5.4, are you still facing the same issue?

**Comment by fakearian** [comment]
@MehediH Same issue unfortunately. And did a clean uninstall/reinstall from the link.

**Comment by fakearian** [comment]
@MehediH idk if this is relevant, but when I went to uninstall version 5.0.3 both times, I saw version 4.7.0 from Jul 12, 2019 in my program files. It wasn't there after uninstall, but when I installed 5.0.3 from the link you replied here, it came back.

**Comment by MehediH** [comment]
> @MehediH idk if this is relevant, but when I went to uninstall version 5.0.3 both times, I saw version 4.7.0 from Jul 12, 2019 in my program files. It wasn't there after uninstall, but when I installed 5.0.3 from the link you replied here, it came back.

That's weird, can you try uninstalling all versions of Tweeten, download 5.0.3, and see if the issue still persists? If so, can you please share the log?

**Comment by fakearian** [comment]
@MehediH Okay I fixed it and I realize it was totally and completely a 'me' problem. When I went to uninstall 5.0.4, I again noticed the weird 4.7.0 pop-up in my list of apps in Windows. So, then I searched all my files to find every instance of Tweeten and deleted any temporary or backlogged files from as long as I've had it. Literally everything, shortcuts included. Finally, when I downloaded 5.0.3 from your link, I could update it to 5.0.4 no problem. Anyways here's the log 

[main.log](https://github.com/MehediH/Tweeten/files/4873813/main.log)

**Comment by MehediH** [comment]
Thank you! I have included a fix in 5.0.5 so hopefully that will improve things

**Comment by Kuroonehalf** [comment]
Same issue happening here. It's been happening for a few versions and I've been having to update manually with a new installer. Right now I'm on version 5.0.4. You say you included a possible fix in 5.0.5. Should I manually update to that, or do you want me to try to obtain information while I'm still on 5.0.4?

I'm on windows 10, with most of the default tweeten settings I think.

**Comment by MehediH** [comment]
@Kuroonehalf There's a possible fix for this in 5.0.5, so the issue will still occur in 5.0.4. If you could share your `config.json` file from `%appdata%/Tweeten` and the `main.log` file from `%appdata%/Tweeten/logs` that would be great!

**Comment by Kuroonehalf** [comment]
Here you go. There was also a main.old.log file in there, I bundled it in.
[main.zip](https://github.com/MehediH/Tweeten/files/4882150/main.zip)

**Comment by MehediH** [comment]
@Kuroonehalf Thanks! I would appreciate it if you could let me know if this issue persists when updating from 5.0.5 to a newer version (once that's released)

**Comment by Kuroonehalf** [comment]
Will do. :>

**Comment by Kuroonehalf** [comment]
Hi. I can confirm that this problem persists. Same deal as last time, there's a notification to update to 5.1.0, I click Install Now, the program closes and the computer lags for a few seconds but then nothing happens. I manually launch the program again and it's still on 5.0.5.

Here's the main.log file.

[main.zip](https://github.com/MehediH/Tweeten/files/5052520/main.zip)
